* sequence_processing
some scripts to process fasta and fastq sequences
** remove duplicates
This script takes a fasta file from STDIN, removes duplicated sequences
and writes the output to STDOUT.

Sequences will be deleted, if they have an identical header and an identical sequence.
This script can also clean the fasta file: Linebreaks in the sequence as well as empty
lines and leading whitespaces in headers (> id) are removed by default. Additionally,
non ACGT charachters are converted to N. This feature can be skipped using the --no-convert
option. The script also converts lowercase sequence characters to uppercase. This can be 
skipped with the --no-up option.

Use one the following commands for help:
#+BEGIN_SRC sh
./remove_dulicates --help
perldoc ./remove_duplicates
#+END_SRC

** sample from fasta
This script takes a fasta file and a number of sequences (n) to sample. It writes n 
randomly selected sequences to the output file.
  
This script can also clean the fasta file: Linebreaks in the sequence as well as empty
lines and leading whitespaces in headers (> id) are removed by default. Additionally,
non ACGT charachters can be converted to N and lowercase sequence characters can be 
converted to uppercase.

Use the following command for help:
#+BEGIN_SRC sh
./sample_from_fasta.pl --help
#+END_SRC

** split fasta
This script takes a fasta file and generates a new file for each sequence. 
The new files are named as <input.fa>.sequenceID

This script will also clean the fasta file: Linebreaks in the sequence as well as empty
lines and leading whitespaces in headers (> id) are removed by default. Additionally,
non ACGT charachters can be converted to N and lowercase sequence characters can be 
converted to uppercase.

Use the following command for help:
#+BEGIN_SRC sh
./sample_from_fasta.pl --help
#+END_SRC
